services:
  ollama:
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama
    ports:
      - "11434:11434"
    tty: true
    restart: always
    volumes:
      - ./ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
