services:
  ollama:
    build: .
    container_name: ollama
    ports:
      - "11434:11434"
    tty: true
    restart: always
    volumes:
      - ./ollama_data:/root/.ollama
      - ./config/config.yaml:/app/config.yaml

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
