qdrant:
  host: "qdrant"
  port: 6333
  collection_name: "my_collection"

chunking:
  chunk_size: 1000
  chunk_overlap: 100
  separators: ["\n\n", "\n", " ", ""]

hf:
  hf_token: "YOUR_HF_TOKEN"
  hf_embedding_model: "Alibaba-NLP/gte-multilingual-base"

ollama:
  model: "deepseek-r1:1.5b"
  base_url: "http://ollama:11434/v1"
